### ISSUE TITLE
TRADFRI Shortcut-Button

### ISSUE THREAD

**Issue by dbu828** [AlCalzone/node-tradfri-client#493] opened 2021-05-10 07:52 UTC
Hi 
Is there a plan to integrate The shortcut button?
I can see the Button but only with status alive, batteryPercentage, lastSeen.
would be nice to have a buttonPressed.

**Comment by AlCalzone** [comment] 2021-05-10 07:59
Unless anything changed in the gateway firmware, this is not possible.

Duplicate of #302
Duplicate of #273

**Closed by AlCalzone** 2021-05-10 07:59 UTC

**Comment by reneroth** [comment] 2024-02-12 19:17
FWIW (and to anyone coming here from the search), what worked for me (although convoluted) was that I had a lightbulb that I used to display "status messages" (new email, stuff like that), which I set to a specific color via a scene when the shortcut button was clicked. Then I polled the bulb for that color, executed my action and turned it off... really convoluted, but fun to get it working from a hacker-perspective.
