### ISSUE TITLE
Support for new Trådfri dimmable remote

### ISSUE THREAD

**Issue by WillooWisp** [AlCalzone/node-tradfri-client#302] opened 2019-12-15 15:54 UTC
Please add support for the new dimmable remote, https://www.ikea.com/se/sv/p/tradfri-tradloes-dimmer-vit-70408595/.

**Comment by AlCalzone** [comment] 2019-12-15 16:54
Duplicate of https://github.com/AlCalzone/node-tradfri-client/issues/273

**Closed by AlCalzone** 2019-12-15 16:54 UTC
